// file: /src/app/layout.tsx

import React from 'react'
import { Inter } from 'next/font/google'
import '@/app/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        <header>
          <nav>
            {/* Add your navigation links here */}
          </nav>
        </header>
        <main>{children}</main>
        <footer>
          {/* Add your footer content here */}
        </footer>
      </body>
    </html>
  )
}